/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import UserRemote.DonViTinh;
import UserRemote.LoaiThuoc;
import UserRemote.Thuoc;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas Nguyen
 */
public class frmThuoc extends javax.swing.JFrame {

    /**
     * Creates new form frmThuoc
     */
    RMI_Client rmi_client;
    DefaultTableModel dtm;
    Thuoc th;

    public frmThuoc() {
        initComponents();
        setLocationRelativeTo(null);
        rmi_client = new RMI_Client();
        ShowData();
        ShowComMaLThuoc();
        ShowComMaDonVT();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaThuoc = new javax.swing.JTextField();
        txtTenThuoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGiaMua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboMaLoaiThuoc = new javax.swing.JComboBox<String>();
        txtDonGiaBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboMaDVT = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thuốc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 16), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã thuốc");

        txtMaThuoc.setPreferredSize(new java.awt.Dimension(25, 25));

        txtTenThuoc.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên thuốc");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã đơn vị tính");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng");

        txtSoLuong.setPreferredSize(new java.awt.Dimension(25, 25));

        txtDonGiaMua.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá mua");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Đơn giá bán");

        cboMaLoaiThuoc.setPreferredSize(new java.awt.Dimension(25, 25));
        cboMaLoaiThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaLoaiThuocActionPerformed(evt);
            }
        });

        txtDonGiaBan.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Mã loại thuốc");

        cboMaDVT.setPreferredSize(new java.awt.Dimension(25, 25));
        cboMaDVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaDVTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMaDVT, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE))
                    .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMaLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboMaLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGiaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDonGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cboMaDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tableThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tableThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Mã đơn vị tính", "Số lượng", "Đơn giá mua", "Đơn giá bán", "Mã loại thuốc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableThuoc.setToolTipText("");
        tableThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableThuoc);

        btnLuu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-list-add-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button-Close-icon.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-validated-icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem)
                    .addComponent(btnLuu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(65, 65, 65)
                        .addComponent(btnThem)
                        .addGap(56, 56, 56)
                        .addComponent(btnThoat)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnThoat)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowData() {
        try {
            ArrayList<Thuoc> listThuoc = rmi_client.user.LoadThuocs();
            dtm = (DefaultTableModel) tableThuoc.getModel();//thêm dữ liêu vào tablenguoidung
            Object[] obj = new Object[7];
            for (int i = 0; i < listThuoc.size(); i++) {
                obj[0] = listThuoc.get(i).getMaThuoc();
                obj[1] = listThuoc.get(i).getTenThuoc();
                obj[2] = listThuoc.get(i).getMaDVT();
                obj[3] = listThuoc.get(i).getSoLuong();
                obj[4] = listThuoc.get(i).getDonGiaMua();
                obj[5] = listThuoc.get(i).getDonGiaBan();
                obj[6] = listThuoc.get(i).getMaLoaiThuoc();
                dtm.addRow(obj);//Thêm một dòng vào dm
            }
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(null, "Lỗi " + e);

        }
    }

    private void ShowComMaLThuoc() {
        try {
            ArrayList<LoaiThuoc> listThuoc = rmi_client.user.LoadComLThuoc();
            for (int i = 0; i < listThuoc.size(); i++) {
                cboMaLoaiThuoc.addItem(listThuoc.get(i).getMaLoaiThuoc());
            }
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(null, "Lỗi " + e);

        }
    }

    private void ShowComMaDonVT() {
        try {
            ArrayList<DonViTinh> listDVT = rmi_client.user.LoadComDonVT();
            for (int i = 0; i < listDVT.size(); i++) {
                cboMaDVT.addItem(listDVT.get(i).getMaDVT());
            }
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(null, "Lỗi " + e);

        }
    }
    private void cboMaLoaiThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaLoaiThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMaLoaiThuocActionPerformed

    private void tableThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThuocMouseClicked
        int row = tableThuoc.getSelectedRow();
        txtMaThuoc.setText(String.valueOf(tableThuoc.getValueAt(row, 0)));
        txtTenThuoc.setText(String.valueOf(tableThuoc.getValueAt(row, 1)));
        cboMaDVT.setSelectedItem(String.valueOf(tableThuoc.getValueAt(row, 2)));
        txtSoLuong.setText(String.valueOf(tableThuoc.getValueAt(row, 3)));
        txtDonGiaMua.setText(String.valueOf(tableThuoc.getValueAt(row, 4)));
        txtDonGiaBan.setText(String.valueOf(tableThuoc.getValueAt(row, 5)));
        cboMaLoaiThuoc.setSelectedItem(String.valueOf(tableThuoc.getValueAt(row, 6)));
        // TODO add your handling code here:
    }//GEN-LAST:event_tableThuocMouseClicked

    private void cboMaDVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaDVTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMaDVTActionPerformed
    private boolean validation() {
        if (txtMaThuoc.getText().equals("") || txtTenThuoc.getText().equals("")
                || txtSoLuong.getText().equals("") || txtDonGiaBan.getText().equals("")
                || txtDonGiaMua.getText().equals("")) {
            return false;
        }
        return true;
    }
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

        String maThuoc = txtMaThuoc.getText();
        String tenThuoc = txtTenThuoc.getText();
        String maDVT = cboMaDVT.getSelectedItem().toString();
        String soLuong = txtSoLuong.getText();
        String donGiaMua = txtDonGiaMua.getText();
        String donGiaBan = txtDonGiaBan.getText();
        String maLThuoc = cboMaLoaiThuoc.getSelectedItem().toString();
        if (validation()) {
            try {
                th = new Thuoc(maThuoc, tenThuoc, maDVT, Integer.parseInt(soLuong), Double.parseDouble(donGiaMua), Double.parseDouble(donGiaBan), maLThuoc);
                int res = rmi_client.user.ThemThuoc(th);
//                System.err.println(res);
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Lưu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    dtm.setRowCount(0);
                    ShowData();
                } else {
                    JOptionPane.showMessageDialog(null, "Đã tồn tại mã thuốc", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(frmThuoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền đủ thông tin", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int dongdachon = tableThuoc.getSelectedRow();
        if (dongdachon == -1) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng cần xóa");
        } else {
            int[] index = tableThuoc.getSelectedRows();//lấy chỉ mục trong bảng khi người dùng click để xóa
            for (int i = 0; i < index.length; i++) {
                String indexDelete = tableThuoc.getValueAt(index[i], 0).toString();//chuyển sang chuỗi
                try {
                    rmi_client.user.XoaThuoc(indexDelete);//đưa qua server xử lý xóa dữ liệu trong CSDL
                } catch (RemoteException ex) {
                    Logger.getLogger(frmThuoc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            dtm.setRowCount(0);//đặt số dòng về 0
            ShowData();//load lại dữ liệu vào bảng sau khi xóa
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtMaThuoc.setText("");
        txtTenThuoc.setText("");
        txtSoLuong.setText("");
        txtDonGiaMua.setText("");
        txtDonGiaBan.setText("");
        txtMaThuoc.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String maThuoc = txtMaThuoc.getText();
        String tenThuoc = txtTenThuoc.getText();
        String maDVT = cboMaDVT.getSelectedItem().toString();
        String soLuong = txtSoLuong.getText();
        String donGiaMua = txtDonGiaMua.getText();
        String donGiaBan = txtDonGiaBan.getText();
        String maLThuoc = cboMaLoaiThuoc.getSelectedItem().toString();
        if (validation()) {
            try {
                th = new Thuoc(maThuoc, tenThuoc, maDVT, Integer.parseInt(soLuong),
                        Double.parseDouble(donGiaMua), Double.parseDouble(donGiaBan), maLThuoc);
                rmi_client.user.CapNhatThuoc(th);
                dtm.setRowCount(0);
                ShowData();
            } catch (RemoteException ex) {
                Logger.getLogger(frmThuoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn chưa điền thông tin cần sửa");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String search = txtTimKiem.getText();
        try {

            ArrayList<Thuoc> listThuoc = rmi_client.user.TimKiemThuoc(search);
            dtm = (DefaultTableModel) tableThuoc.getModel();//thêm dữ liêu vào tablenguoidung
            dtm.setRowCount(0);
            Object[] obj = new Object[7];
            for (int i = 0; i < listThuoc.size(); i++) {
                obj[0] = listThuoc.get(i).getMaThuoc();
                obj[1] = listThuoc.get(i).getTenThuoc();
                obj[2] = listThuoc.get(i).getMaDVT();
                obj[3] = listThuoc.get(i).getSoLuong();
                obj[4] = listThuoc.get(i).getDonGiaMua();
                obj[5] = listThuoc.get(i).getDonGiaBan();
                obj[6] = listThuoc.get(i).getMaLoaiThuoc();
                dtm.addRow(obj);//Thêm một dòng vào dm
            }
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(null, "Lỗi " + e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaDVT;
    private javax.swing.JComboBox<String> cboMaLoaiThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThuoc;
    private javax.swing.JTextField txtDonGiaBan;
    private javax.swing.JTextField txtDonGiaMua;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenThuoc;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
